# Changes whalesay to speak a fortune
#FROM docker/whalesay:latest
#RUN apt-get -y update && apt-get install -y fortunes
#CMD /usr/games/fortune -a | cowsay

# example with curl
FROM ubuntu:latest
RUN apt-get -y update && apt-get install -y curl